version: '3.8'
services:
  cellular:
    container_name: cellular
    # restart: always
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db
    volumes:
    - .:/app

  db:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db:
    driver: local